### ISSUE TITLE
Screenshots for all examples

### ISSUE THREAD

**Issue by radimvaculik** [petrnohejl/Android-Templates-And-Utilities#1]
It would be great if each template should has own screenshot.

**Comment by petrnohejl** [comment]
Thanks for suggestion, Radim. It is a good idea. Some templates are not UI templates, so I can't provide any screenshot. Example fragments just show how to use a specific template/utility in practice. I could probably provide screenshots for following templates. Maybe I could also describe each template - what is it good for. 
- ~~Res-Menu~~
- Res-Shapes
- Res-Style
- Src-ActionBar-Done-Bar
- Src-ActionBar-List-Navigation
- ~~Src-ActionBar-Pull-To-Refresh~~
- Src-ActionBar-Refresh
- Src-ActionBar-Search
- Src-AspectRatioImageView
- ~~Src-Dialog-Style~~
- ~~Src-DialogFragment~~
- Src-Dual-Pane
- Src-EllipsizingTextView
- ~~Src-ExpandableListView~~
- ~~Src-Fragment~~
- ~~Src-ListFragment~~
- ~~Src-Map~~
- Src-MaxWidthLinearLayout
- ~~Src-Navigation-Drawer~~
- ~~Src-PreferenceFragment~~
- Src-RotatableImageView
- ~~Src-StickyListView~~
- ~~Src-SwipeRefreshLayout~~
- Src-ViewPager

**Comment by johnjohndoe** [comment]
:+1:

**Comment by petrnohejl** [comment]
I added some screenshots: https://github.com/petrnohejl/Android-Templates-And-Utilities/commit/20c1c120b568eb2e4bc3c0773bcc2612b249c7a1, https://github.com/petrnohejl/Android-Templates-And-Utilities/commit/8789272e53e2c56009922398063369edb870a413. More screenshots later...

**Comment by petrnohejl** [comment]
I updated all screenshots: https://github.com/petrnohejl/Android-Templates-And-Utilities/commit/8483d49f602d80e4c4b92c262da63960835064d1.
