### ISSUE TITLE
Non-translatable string in strings.xml is missing the appropriate attribute

### ISSUE THREAD

**Issue by SufianBabri** [petrnohejl/Android-Templates-And-Utilities#7]
Just saw the [strings.xml](https://github.com/petrnohejl/Android-Templates-And-Utilities/blob/master/Res-Strings/values/strings.xml) and wanted to point out that for any non-translatable string, you should add `translatable="false"`.

For example:

```
<string name="app_name"  translatable="false">Example</string>
```

More about [Non-translatable Strings](http://tools.android.com/recent/non-translatablestrings).

**Comment by Beautiful06** [comment]
<string name="app_name"  translatable="false">Example</string>

**Comment by Beautiful06** [comment]
translatable="false".

**Comment by petrnohejl** [comment]
Thank you. I already have this in my TODO list. I will fix it.
